<a href="https://colab.research.google.com/github/av1sh3k-bd/KEGG2/blob/main/ec_to_gene.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [ ]:
!pip install Bio

In [ ]:
!pip install Biopython

In [ ]:
!pip install beautifulsoup4

In [4]:
# Show plots as part of the notebook
%matplotlib inline

# Show images inline
from IPython.display import Image

# Standard library packages
import io
import os

# Import Biopython modules to interact with KEGG
from Bio import SeqIO
from Bio.KEGG import REST
from Bio.KEGG.KGML import KGML_parser

In [5]:
# Some code to return a Pandas dataframe, given tabular text
def to_df(result):
    return pd.read_table(io.StringIO(result), header=None)

In [6]:
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (4.6.3)

In [7]:
from urllib.request import urlopen
from bs4 import BeautifulSoup

In [8]:
import re

In [9]:
# specify the url
url = "https://www.genome.jp/pathway/bit01100+M00793"

# Connect to the website and return the html to the variable ‘page’
try:
    page = urlopen(url)
except:
    print("Error opening the URL")

# parse the html using beautiful soup and store in variable `soup`
soup = BeautifulSoup(page, 'html.parser')

# Take out the <div> of name and get its value
content = soup.find('ul', {"class": "tree module-tree"})
#print(content)
content=str(content)

In [10]:
# Python program to convert a list to string
    
# Function to convert  
def listToString(s): 
    
    # initialize an empty string
    str1 = "" 
    
    # traverse in the string  
    for ele in s: 
        str1 += ele  
    
    # return string  
    return str1

In [11]:
#pattern=re.compile(r'k">M\w\w\w\w\w')

#pattern=re.compile(r'blank">M00001</a>\s*(\w*)')

pattern=re.compile(r'>M\w\w\w\w\w</a>\s*[a-zA-Z\s\(\)\-]*')


matches=pattern.findall(content)

matches=listToString(matches)


pattern2=re.compile(r'M\d\d\d\d\d')

map_ids=pattern2.findall(matches)

print(map_ids)

['M00001', 'M00002', 'M00003', 'M00307', 'M00009', 'M00010', 'M00011', 'M00004', 'M00006', 'M00007', 'M00580', 'M00005', 'M00008', 'M00308', 'M00633', 'M00309', 'M00014', 'M00630', 'M00631', 'M00061', 'M00081', 'M00632', 'M00552', 'M00129', 'M00114', 'M00550', 'M00854', 'M00855', 'M00565', 'M00549', 'M00554', 'M00909', 'M00761', 'M00012', 'M00373', 'M00740', 'M00532', 'M00013', 'M00741', 'M00130', 'M00131', 'M00132', 'M00165', 'M00166', 'M00167', 'M00168', 'M00169', 'M00172', 'M00171', 'M00170', 'M00173', 'M00376', 'M00375', 'M00374', 'M00377', 'M00579', 'M00620', 'M00567', 'M00357', 'M00356', 'M00563', 'M00358', 'M00608', 'M00174', 'M00346', 'M00345', 'M00344', 'M00378', 'M00935', 'M00422', 'M00175', 'M00531', 'M00530', 'M00529', 'M00528', 'M00804', 'M00176', 'M00596', 'M00595', 'M00082', 'M00083', 'M00873', 'M00874', 'M00085', 'M00415', 'M00086', 'M00087', 'M00861', 'M00101', 'M00102', 'M00917', 'M00103', 'M00104', 'M00106', 'M00862', 'M00107', 'M00108', 'M00109', 'M00110', 'M00088', 'M00089', 'M00098', 'M00090', 'M00091', 'M00092', 'M00093', 'M00094', 'M00066', 'M00067', 'M00099', 'M00100', 'M00113', 'M00048', 'M00049', 'M00050', 'M00546', 'M00051', 'M00052', 'M00053', 'M00938', 'M00046', 'M00939', 'M00020', 'M00018', 'M00555', 'M00033', 'M00919', 'M00021', 'M00338', 'M00609', 'M00017', 'M00034', 'M00035', 'M00368', 'M00019', 'M00535', 'M00570', 'M00432', 'M00036', 'M00016', 'M00525', 'M00526', 'M00527', 'M00030', 'M00433', 'M00031', 'M00032', 'M00028', 'M00763', 'M00844', 'M00845', 'M00029', 'M00015', 'M00047', 'M00879', 'M00133', 'M00134', 'M00135', 'M00136', 'M00026', 'M00045', 'M00022', 'M00023', 'M00024', 'M00910', 'M00025', 'M00040', 'M00042', 'M00043', 'M00044', 'M00533', 'M00037', 'M00936', 'M00038', 'M00027', 'M00369', 'M00118', 'M00947', 'M00948', 'M00949', 'M00055', 'M00072', 'M00073', 'M00074', 'M00075', 'M00056', 'M00872', 'M00065', 'M00070', 'M00071', 'M00068', 'M00069', 'M00057', 'M00058', 'M00059', 'M00076', 'M00077', 'M00078', 'M00079', 'M00060', 'M00866', 'M00867', 'M00063', 'M00064', 'M00922', 'M00923', 'M00127', 'M00895', 'M00896', 'M00897', 'M00898', 'M00899', 'M00125', 'M00911', 'M00124', 'M00916', 'M00115', 'M00912', 'M00810', 'M00811', 'M00622', 'M00119', 'M00913', 'M00120', 'M00914', 'M00572', 'M00123', 'M00950', 'M00573', 'M00577', 'M00881', 'M00882', 'M00883', 'M00884', 'M00126', 'M00840', 'M00841', 'M00842', 'M00843', 'M00880', 'M00140', 'M00846', 'M00868', 'M00121', 'M00926', 'M00847', 'M00924', 'M00925', 'M00122', 'M00836', 'M00117', 'M00128', 'M00116', 'M00930', 'M00931', 'M00932', 'M00112', 'M00933', 'M00095', 'M00849', 'M00096', 'M00364', 'M00097', 'M00372', 'M00371', 'M00927', 'M00928', 'M00929', 'M00773', 'M00934', 'M00774', 'M00775', 'M00776', 'M00777', 'M00824', 'M00825', 'M00826', 'M00827', 'M00828', 'M00829', 'M00830', 'M00831', 'M00832', 'M00834', 'M00833', 'M00778', 'M00779', 'M00780', 'M00823', 'M00781', 'M00782', 'M00783', 'M00784', 'M00793', 'M00794', 'M00795', 'M00796', 'M00797', 'M00798', 'M00799', 'M00800', 'M00801', 'M00802', 'M00803', 'M00039', 'M00137', 'M00940', 'M00138', 'M00941', 'M00942', 'M00943', 'M00944', 'M00945', 'M00946', 'M00370', 'M00900', 'M00894', 'M00902', 'M00672', 'M00673', 'M00675', 'M00736', 'M00674', 'M00877', 'M00889', 'M00815', 'M00904', 'M00785', 'M00787', 'M00848', 'M00788', 'M00819', 'M00903', 'M00890', 'M00661', 'M00786', 'M00937', 'M00893', 'M00891', 'M00901', 'M00814', 'M00789', 'M00790', 'M00805', 'M00808', 'M00835', 'M00837', 'M00838', 'M00921', 'M00905', 'M00876', 'M00875', 'M00918', 'M00906', 'M00538', 'M00537', 'M00419', 'M00547', 'M00548', 'M00551', 'M00637', 'M00568', 'M00569', 'M00539', 'M00543', 'M00544', 'M00418', 'M00541', 'M00540', 'M00534', 'M00638', 'M00624', 'M00623', 'M00636', 'M00878', 'M00545', 'M00915']

In [13]:
#iterating over map ids to get ec ids
result=""
for ids in map_ids:
  result = result+REST.kegg_link("ec", ids).read()

In [14]:
df1=to_df(result)
df1=df1.rename(columns={0: 'map id', 1: 'ec id'})
df1.head()

      map id         ec id
0  md:M00001    ec:2.7.1.1
1  md:M00001    ec:2.7.1.2
2  md:M00001   ec:2.7.1.63
3  md:M00001  ec:2.7.1.147
4  md:M00001  ec:2.7.1.146

In [ ]:
#print(matches)

pathway_content=re.sub(r'(.*?)>\s*','',matches)
#pathway_content=re.sub(r'(\s)*\w','',pathway_content)

#pathway_content=pathway_content.replace("\n","")

print(pathway_content)

pathway_pattern=re.compile(r'[a-zA-Z]')

pathway_match=pathway_pattern.findall(matches)

for line in textData.splitlines():
    print(line)
    lineResult = libLAPFF.parseLine(line)

In [16]:
pathway_list = pathway_content.split("\n\n")
pathway_list = list(set(pathway_list))   #removes duplicates
print(pathway_list)

['Mithramycin biosynthesis', 'Violacein biosynthesis', 'Caffeine degradation', 'Cronin biosynthesis', 'Tryptophan biosynthesis', 'Ectoine biosynthesis', 'Pentose phosphate pathway (Pentose phosphate cycle)', 'Serine biosynthesis', 'Glyoxylate cycle', 'Polyamine biosynthesis', 'Betaine biosynthesis', 'Gluconeogenesis', 'Heparan sulfate degradation', 'Methionine degradation', 'Glucosinolate biosynthesis', 'Ditryptophenaline biosynthesis', 'Fosfomycin biosynthesis', 'Thyroid hormone biosynthesis', 'Entner-Doudoroff pathway', 'Sphingosine degradation', 'Trans-cinnamate degradation', 'Keratan sulfate degradation', 'Xylene degradation', 'Shikimate pathway', 'Monolignol biosynthesis', 'Phosphatidylcholine (PC) biosynthesis', 'Staphyloferrin B biosynthesis', 'Cobalamin biosynthesis', 'Pyrimidine deoxyribonuleotide biosynthesis', 'Hydroxyproline degradation', 'Grixazone biosynthesis', 'Homoprotocatechuate degradation', 'Abscisic acid biosynthesis', 'Ornithine biosynthesis', 'Phosphate acetyltransferase-acetate kinase pathway', 'beta-Oxidation', 'Biotin biosynthesis', 'Fatty acid elongation in mitochondria', 'Terpentecin biosynthesis', 'Uridine monophosphate biosynthesis', 'Dermatan sulfate degradation', 'Phthalate degradation', 'Glycogen biosynthesis', 'Methylaspartate cycle', 'Pyrimidine ribonucleotide biosynthesis', 'Methionine salvage pathway', 'Aurachin biosynthesis', 'Ketone body biosynthesis', 'Propanoyl-CoA metabolism', 'Maduropeptin beta-hydroxy acid moiety biosynthesis', 'Dapdiamides biosynthesis', 'Undecylprodigiosin biosynthesis', 'Malonate semialdehyde pathway', 'Cholesterol biosynthesis', 'Ethylmalonyl pathway', 'D-Galacturonate degradation (fungi)', 'Staphylopine biosynthesis', 'Cannabidiol biosynthesis', 'Purine degradation', 'Lysine biosynthesis', 'Pyocyanine biosynthesis', 'Toluene degradation', 'Pyrrolnitrin biosynthesis', 'Glycogen degradation', 'Tryptophan metabolism', 'Cyanogenic glycoside biosynthesis', 'Benzoate degradation', 'Methionine biosynthesis', 'Nicotinate degradation', 'Oleandomycin biosynthesis', 'Dissimilatory sulfate reduction', 'Lovastatin biosynthesis', 'Menaquinone biosynthesis', 'Anthranilate degradation', 'dTDP-D-angolosamine biosynthesis', 'Rebeccamycin biosynthesis', '\t\t', 'Avermectin biosynthesis', 'Pyruvate oxidation', 'Carbazole degradation', 'Acetyl-CoA pathway', 'Sphingosine biosynthesis', 'Plastoquinone biosynthesis', 'Thiamine biosynthesis', 'Type II polyketide backbone biosynthesis', 'Phylloquinone biosynthesis', 'dTDP-L-rhamnose biosynthesis', 'Reticuline biosynthesis', 'Ascorbate degradation', 'dTDP-D-forosamine biosynthesis', 'Naphthalene degradation', 'Tetrahydrobiopterin biosynthesis', 'Mycinamicin biosynthesis', 'Cholecalciferol biosynthesis', 'Prodigiosin biosynthesis', 'Pterocarpan biosynthesis', 'Ceramide biosynthesis', 'Terephthalate degradation', 'Erythromycin biosynthesis', 'Lactosylceramide biosynthesis', 'Salicylate degradation', 'Pentalenolactone biosynthesis', 'Phytosterol biosynthesis', 'Aerobactin biosynthesis', 'L-threo-Tetrahydrobiopterin biosynthesis', 'Denitrification', 'Staphyloferrin A biosynthesis', 'Isoleucine biosynthesis', 'Creatine pathway', 'Chondroitin sulfate degradation', 'Cymene degradation', 'Ethynylserine biosynthesis', 'Histidine degradation', 'Acarbose biosynthesis', 'GABA (gamma-Aminobutyrate) shunt', 'Leucine biosynthesis', 'Sulfoglycolipids biosynthesis', 'Elloramycin biosynthesis', 'Ergocalciferol biosynthesis', 'Methanogenesis', 'Acylglycerol degradation', 'Calicheamicin orsellinate moiety biosynthesis', 'dTDP-beta-L-noviose biosynthesis', 'Proline biosynthesis', 'Reductive pentose phosphate cycle (Calvin cycle)', 'dTDP-L-oleandrose biosynthesis', 'Clavaminate biosynthesis', 'Aflatoxin biosynthesis', 'Dicarboxylate-hydroxybutyrate cycle', 'Ectoine degradation', 'Bacilysin biosynthesis', 'Cycloserine biosynthesis', 'Hydroxypropionate-hydroxybutylate cycle', 'Ethylene biosynthesis', 'Triacylglycerol biosynthesis', 'Guanine ribonucleotide biosynthesis', 'Cyclooctatin biosynthesis', 'Bile acid biosynthesis', 'Validamycin A biosynthesis', 'Conjugated bile acid biosynthesis', 'Reductive acetyl-CoA pathway (Wood-Ljungdahl pathway)', 'Threonine biosynthesis', 'Adenine ribonucleotide biosynthesis', 'Glutathione biosynthesis', 'Lipoic acid biosynthesis', 'NAD biosynthesis', 'Morphine biosynthesis', 'CMP-KDO biosynthesis', 'Assimilatory nitrate reduction', 'D-Galacturonate degradation (bacteria)', 'Castasterone biosynthesis', 'Nocardicin A biosynthesis', 'Noscapine biosynthesis', 'Thiosulfate oxidation by SOX complex', 'Inositol phosphate metabolism', 'Nitrogen fixation', 'Assimilatory sulfate reduction', 'Inosine monophosphate biosynthesis', 'Penicillin biosynthesis', 'Nitrification', 'dTDP-D-mycaminose biosynthesis', 'Pyridoxal-P biosynthesis', 'Trehalose biosynthesis', 'Isoflavone biosynthesis', 'Nucleotide sugar biosynthesis', 'N-glycosylation by oligosaccharyltransferase', 'Non-phosphorylative Entner-Doudoroff pathway', 'Chlortetracycline biosynthesis', 'Benzene degradation', 'dTDP-D-desosamine biosynthesis', 'Phenylacetate degradation', 'Arginine biosynthesis', 'Dissimilatory nitrate reduction', 'Cumate degradation', 'Glycolysis (Embden-Meyerhof pathway)', 'Methanofuran biosynthesis', 'Jasmonic acid biosynthesis', 'Podophyllotoxin biosynthesis', 'Phosphatidylethanolamine (PE) biosynthesis', 'Photorespiration', 'Pantothenate biosynthesis', 'Sanguinarine biosynthesis', 'Coenzyme A biosynthesis', 'Siroheme biosynthesis', 'Pyrimidine degradation', 'N-glycan precursor trimming', 'Incomplete reductive citrate cycle', 'Semi-phosphorylative Entner-Doudoroff pathway', 'Reductive pentose phosphate cycle', 'Calicheamicin biosynthesis', 'Arginine succinyltransferase pathway', 'Leucine degradation', 'D-Arginine racemization', 'Fumitremorgin alkaloid biosynthesis', 'Staurosporine biosynthesis', 'Coenzyme M biosynthesis', 'Biphenyl degradation', 'D-Glucuronate degradation', 'Roseoflavin biosynthesis', 'Catechol ortho-cleavage', 'beta-Carotene biosynthesis', 'Reductive citrate cycle (Arnon-Buchanan cycle)', 'dTDP-L-megosamine biosynthesis', 'Molybdenum cofactor biosynthesis', 'Cysteine biosynthesis', 'Flavonoid biosynthesis', 'Tyrosine degradation', 'Cephamycin C biosynthesis', 'Steroid hormone biosynthesis', 'UDP-L-FucNAm biosynthesis', 'PRPP biosynthesis', 'dTDP-L-olivose biosynthesis', 'Thiamine salvage pathway', 'Puromycin biosynthesis', 'Catechol meta-cleavage', 'Fatty acid elongation in endoplasmic reticulum', 'ADP-L-glycero-D-manno-heptose biosynthesis', 'Neocarzinostatin naphthoate moiety biosynthesis', 'Glucuronate pathway (uronate pathway)', 'Pectin degradation', 'Fumiquinazoline biosynthesis', 'Dihydrokalafungin biosynthesis', 'Catecholamine biosynthesis', 'Paspaline biosynthesis', 'Benzoyl-CoA degradation', 'Tetrahydrofolate biosynthesis', 'Phenylalanine biosynthesis', 'Tylosin biosynthesis', 'N-glycan precursor biosynthesis', 'dTDP-L-mycarose biosynthesis', 'Lysine degradation', 'Urea cycle', 'Flavanone biosynthesis', 'Tyrosine biosynthesis', 'Histidine biosynthesis']

In [ ]:
temp = REST.kegg_list("pathway", "bis").read()
to_df(temp)

In [ ]:
genes = REST.kegg_list("bis").read()
to_df(genes)

In [20]:
temp = REST.kegg_link("genes", "K00501").read()
to_df(temp)

             0                       1
0    ko:K00501                hsa:7054
1    ko:K00501              ptr:450955
2    ko:K00501           pps:100967895
3    ko:K00501           ggo:101135345
4    ko:K00501           pon:100454349
..         ...                     ...
517  ko:K00501  msag:GCM10017556_43150
518  ko:K00501         gog:C1280_12450
519  ko:K00501         gms:SOIL9_61730
520  ko:K00501           ftj:FTUN_0679
521  ko:K00501        tsph:KIH39_06910

[522 rows x 2 columns]

In [34]:
#iterating over ec ids to get ko
res_ec_ko=""
for ids in df1['ec id'].tolist():
  #print(ids)
  res_ec_ko = res_ec_ko+REST.kegg_link("ko", ids).read()

In [38]:
df2_ec_ko=to_df(res_ec_ko)
df2_ec_ko=df2_ec_ko.rename(columns={0: 'ec id', 1: 'ko id'})
df2_ec_ko.head()

         ec id      ko id
0   ec:2.7.1.1  ko:K00844
1   ec:2.7.1.2  ko:K00845
2   ec:2.7.1.2  ko:K12407
3   ec:2.7.1.2  ko:K25026
4  ec:2.7.1.63  ko:K00886

In [45]:
#iterating over ko ids to get genes
res_ko_gene=""
for ids in df2_ec_ko['ko id'].tolist():
  #print(ids)
  res_ko_gene = res_ko_gene+REST.kegg_link("bis", ids).read()

In [51]:
df_ko_gene=to_df(res_ko_gene)
df_ko_gene=df_ko_gene.rename(columns={0: 'ko id', 1: 'gene'})
df_ko_gene

         ko id              gene
0    ko:K25026  bis:DXK01_002035
1    ko:K25026  bis:DXK01_018955
2    ko:K25026  bis:DXK01_009870
3    ko:K25026  bis:DXK01_000635
4    ko:K01810  bis:DXK01_000045
..         ...               ...
927  ko:K13789  bis:DXK01_022145
928  ko:K13789  bis:DXK01_022145
929  ko:K01607  bis:DXK01_002690
930  ko:K01912  bis:DXK01_019090
931  ko:K01912  bis:DXK01_017485

[932 rows x 2 columns]

In [147]:
df_ec_ko_gene=pd.merge(df2_ec_ko,df_ko_gene, on='ko id')
df_ec_ko_gene

             ec id      ko id              gene
0       ec:2.7.1.2  ko:K25026  bis:DXK01_002035
1       ec:2.7.1.2  ko:K25026  bis:DXK01_018955
2       ec:2.7.1.2  ko:K25026  bis:DXK01_009870
3       ec:2.7.1.2  ko:K25026  bis:DXK01_000635
4       ec:2.7.1.2  ko:K25026  bis:DXK01_002035
...            ...        ...               ...
3715  ec:1.1.1.133  ko:K00067  bis:DXK01_021180
3716  ec:2.1.1.104  ko:K00588  bis:DXK01_006405
3717   ec:4.1.1.44  ko:K01607  bis:DXK01_002690
3718   ec:6.2.1.30  ko:K01912  bis:DXK01_019090
3719   ec:6.2.1.30  ko:K01912  bis:DXK01_017485

[3720 rows x 3 columns]

In [54]:
import urllib3  # the lib that handles the url stuff

In [55]:
import urllib.request

In [ ]:
with urllib.request.urlopen('https://www.genome.jp/dbget-bin/www_bget?-f+-n+n+'+'bis:DXK01_002035') as response:
   
   content = response.read().decode()
   soup = BeautifulSoup(content, 'html.parser')
   content = str(soup.find('pre'))
   content="\n".join(content.split("\n")[2:-1])  #prints only the gene sequence
   #print(content)
print(content)

In [120]:
def generateSequence(gene_name):
  with urllib.request.urlopen('https://www.genome.jp/dbget-bin/www_bget?-f+-n+n+'+'bis:DXK01_002035') as response:
   
    content = response.read().decode()
    soup = BeautifulSoup(content, 'html.parser')
    content = str(soup.find('pre'))
    content="\n".join(content.split("\n")[2:-1])  #prints only the gene sequence
    return content

In [121]:
print(generateSequence("bis:DXK01_018955"))

atgaattcaagcatggaaaaaccctacgtagtaggtattgacataggcggaacaaacacc
gtctttggtattgtagatgcacgtggaactattattgcaagcggctctatcaaaaccggc
gctcacgaacaagtagataattatgtagacgaagtctgcaaaaatctgttacctttgatt
atcgccaacggtggcgtagacaaaattaaaggtatcggtattggtgctcccaacggtaac
tactacagcggtactattgaatttgcccctaacttgccctggaaaggtgtaattcctttg
gcagccatgtttgaggaacgtctgggtatcccgactgcattgacgaacgacgccaacgcc
gcagctatcggtgaaatgacttatggtgctgcacgtggtatgaaagatttcatcatgatc
actctgggtacaggtgtaggtagcggtatcgttatcaacggtcagatggtttatggtcac
gatggttttgccggagaattaggtcacgtcatcatacgtcgcgagaacggtcgtctctgc
ggatgcggacgtcatggctgcttggaaacttactgttcggctaccggtgtagctcgtaca
gcccgtgaattcctaactgcacgtaccgagccaagtttgcttcgttctattcctgctgaa
aatatcacgtctaaagatgtgtacgatgcagccgttcaaggtgacaaacttgcacaagat
atcttcaactttacaggtactatcctgggtgaagctatagcagatgctatcgcattctcc
agccccgaagctatcatcctgtttggtggattggctaaatccggagattatatcttcaaa
cctatccagaaagctatcgatgacaatgtgctgaatatctataaaggtaaagccaagttg
ttgatgtctgaattaaaagattccgatgctgctgtattaggtgccagtgcattgggctgg
gaactaagagacttgaagtaa

In [ ]:
#iterating over genes to get gene sequence

res_gen_seq=[]
for ids in df_ko_gene['gene'].tolist():
  #print(ids)
  res_gen_seq.append(generateSequence(ids))
res_gen_seq[3]

In [126]:
print(res_gen_seq[3])

atgaattcaagcatggaaaaaccctacgtagtaggtattgacataggcggaacaaacacc
gtctttggtattgtagatgcacgtggaactattattgcaagcggctctatcaaaaccggc
gctcacgaacaagtagataattatgtagacgaagtctgcaaaaatctgttacctttgatt
atcgccaacggtggcgtagacaaaattaaaggtatcggtattggtgctcccaacggtaac
tactacagcggtactattgaatttgcccctaacttgccctggaaaggtgtaattcctttg
gcagccatgtttgaggaacgtctgggtatcccgactgcattgacgaacgacgccaacgcc
gcagctatcggtgaaatgacttatggtgctgcacgtggtatgaaagatttcatcatgatc
actctgggtacaggtgtaggtagcggtatcgttatcaacggtcagatggtttatggtcac
gatggttttgccggagaattaggtcacgtcatcatacgtcgcgagaacggtcgtctctgc
ggatgcggacgtcatggctgcttggaaacttactgttcggctaccggtgtagctcgtaca
gcccgtgaattcctaactgcacgtaccgagccaagtttgcttcgttctattcctgctgaa
aatatcacgtctaaagatgtgtacgatgcagccgttcaaggtgacaaacttgcacaagat
atcttcaactttacaggtactatcctgggtgaagctatagcagatgctatcgcattctcc
agccccgaagctatcatcctgtttggtggattggctaaatccggagattatatcttcaaa
cctatccagaaagctatcgatgacaatgtgctgaatatctataaaggtaaagccaagttg
ttgatgtctgaattaaaagattccgatgctgctgtattaggtgccagtgcattgggctgg
gaactaagagacttgaagtaa

In [ ]:
df_gen_seq = pd.DataFrame(columns = ['gene', 'gene_sequence'])
for i,ids in enumerate(df_ko_gene['gene'].tolist()):
  #print(ids)
  print(i)
  df_gen_seq=df_gen_seq.append({'gene':ids, 'gene_sequence':res_gen_seq[i]},ignore_index = True)
df_gen_seq

In [141]:
#iterating over genes to get gene sequence
df_gen_seq = pd.DataFrame(columns = ['gene', 'gene_sequence'])
res_gen_seq=[]
for ids in df_ko_gene['gene'].tolist():
  #print(ids)
  res_gen_seq.append(generateSequence(ids))
  df_gen_seq=df_gen_seq.append({'gene':ids, 'gene_sequence':generateSequence(ids)},ignore_index = True)

In [142]:
df_gen_seq

                 gene                                      gene_sequence
0    bis:DXK01_002035  atgaattcaagcatggaaaaaccctacgtagtaggtattgacatag...
1    bis:DXK01_018955  atgaattcaagcatggaaaaaccctacgtagtaggtattgacatag...
2    bis:DXK01_009870  atgaattcaagcatggaaaaaccctacgtagtaggtattgacatag...
3    bis:DXK01_000635  atgaattcaagcatggaaaaaccctacgtagtaggtattgacatag...
4    bis:DXK01_000045  atgaattcaagcatggaaaaaccctacgtagtaggtattgacatag...
..                ...                                                ...
927  bis:DXK01_022145  atgaattcaagcatggaaaaaccctacgtagtaggtattgacatag...
928  bis:DXK01_022145  atgaattcaagcatggaaaaaccctacgtagtaggtattgacatag...
929  bis:DXK01_002690  atgaattcaagcatggaaaaaccctacgtagtaggtattgacatag...
930  bis:DXK01_019090  atgaattcaagcatggaaaaaccctacgtagtaggtattgacatag...
931  bis:DXK01_017485  atgaattcaagcatggaaaaaccctacgtagtaggtattgacatag...

[932 rows x 2 columns]

In [150]:
df_ec_ko_gene_seq=pd.merge(df_ec_ko_gene,df_gen_seq, on='gene')
df_ec_ko_gene_seq

              ec id  ...                                      gene_sequence
0        ec:2.7.1.2  ...  atgaattcaagcatggaaaaaccctacgtagtaggtattgacatag...
1        ec:2.7.1.2  ...  atgaattcaagcatggaaaaaccctacgtagtaggtattgacatag...
2        ec:2.7.1.2  ...  atgaattcaagcatggaaaaaccctacgtagtaggtattgacatag...
3        ec:2.7.1.2  ...  atgaattcaagcatggaaaaaccctacgtagtaggtattgacatag...
4        ec:2.7.1.2  ...  atgaattcaagcatggaaaaaccctacgtagtaggtattgacatag...
...             ...  ...                                                ...
21879  ec:1.1.1.133  ...  atgaattcaagcatggaaaaaccctacgtagtaggtattgacatag...
21880  ec:2.1.1.104  ...  atgaattcaagcatggaaaaaccctacgtagtaggtattgacatag...
21881   ec:4.1.1.44  ...  atgaattcaagcatggaaaaaccctacgtagtaggtattgacatag...
21882   ec:6.2.1.30  ...  atgaattcaagcatggaaaaaccctacgtagtaggtattgacatag...
21883   ec:6.2.1.30  ...  atgaattcaagcatggaaaaaccctacgtagtaggtattgacatag...

[21884 rows x 4 columns]

In [152]:
from google.colab import files

df_ec_ko_gene_seq.to_csv('out.csv')
files.download('out.csv')